format_version: '1.0'

# old file name: afterrec_false-unreach-call_true-termination.c
input_files: 'afterrec-1.c'

properties:
  - property_file: ../properties/termination.prp
    expected_verdict: true
  - property_file: ../properties/unreach-call.prp
    expected_verdict: false
