format_version: '1.0'

# old file name: id2_i5_o5_true-unreach-call_true-termination.c
input_files: 'id2_i5_o5-2.c'

properties:
  - property_file: ../properties/termination.prp
    expected_verdict: true
  - property_file: ../properties/unreach-call.prp
    expected_verdict: true
