format_version: '1.0'

# old file name: id_i25_o25_true-unreach-call_true-termination.c
input_files: 'id_i25_o25-1.c'

properties:
  - property_file: ../properties/termination.prp
    expected_verdict: true
  - property_file: ../properties/unreach-call.prp
    expected_verdict: true
