format_version: '1.0'

# old file name: MADWiFi-encode_ie_ok_true-unreach-call_true-termination.i
input_files: 'MADWiFi-encode_ie_ok.i'

properties:
  - property_file: ../properties/termination.prp
    expected_verdict: true
  - property_file: ../properties/unreach-call.prp
    expected_verdict: true
  - property_file: ../properties/coverage-branches.prp
  - property_file: ../properties/coverage-conditions.prp
  - property_file: ../properties/coverage-statements.prp
