format_version: '1.0'

# old file name: AliasDarteFeautrierGonnord-SAS2010-random1d_true-termination_true-no-overflow.c
input_files: 'AliasDarteFeautrierGonnord-SAS2010-random1d-2.c'

properties:
  - property_file: ../properties/no-overflow.prp
    expected_verdict: true
  - property_file: ../properties/termination.prp
    expected_verdict: true
