format_version: '1.0'

# old file name: Ben-Amram-LMCS2010-Ex2.3_false-no-overflow.c
input_files: 'Ben-Amram-LMCS2010-Ex2.3.c'

properties:
  - property_file: ../properties/no-overflow.prp
    expected_verdict: false
