format_version: '1.0'

# old file name: GopanReps-CAV2006-Fig1a_true-termination_true-no-overflow.c.c
input_files: 'GopanReps-CAV2006-Fig1a.c'

properties:
  - property_file: ../properties/no-overflow.prp
    expected_verdict: true
  - property_file: ../properties/termination.prp
    expected_verdict: true
