format_version: '1.0'

# old file name: GulwaniJainKoskinen-PLDI2009-Fig1_false-no-overflow.c
input_files: 'GulwaniJainKoskinen-PLDI2009-Fig1.c'

properties:
  - property_file: ../properties/no-overflow.prp
    expected_verdict: false
