format_version: '1.0'

# old file name: LeeJonesBen-Amram-POPL2001-Ex4_true-termination_true-no-overflow.c
input_files: 'LeeJonesBen-Amram-POPL2001-Ex4.c'

properties:
  - property_file: ../properties/no-overflow.prp
    expected_verdict: true
  - property_file: ../properties/termination.prp
    expected_verdict: true
